{{- if .Values.localStorage.create -}}
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: local-storage-dir
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
    openebs.io/cas-type: local
    cas.openebs.io/config: |
      - name: StorageType
        value: {{ .Values.localStorage.storageType }}
      - name: BasePath
        value: {{ .Values.localStorage.basePath }}
provisioner: openebs.io/local
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
{{- end }}